import NavigationBar from '@/components/navigation-bar'
import { SidebarProvider } from '@/components/ui/sidebar'
import type { Metadata } from 'next'
import './globals.css'
import Header from '@/components/header'
import { Inter } from 'next/font/google'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const inter = Inter({ subsets: ['vietnamese'] })

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased`}>
        <div className="flex h-screen">
          <SidebarProvider>
            <NavigationBar />
            <main className="flex-1">
              <Header />
              {children}
            </main>
          </SidebarProvider>
        </div>
      </body>
    </html>
  )
}
